### ISSUE TITLE
need data resource to test,  can upload it?

### ISSUE THREAD

**Issue by digitalgust** [moefh/baroque#1]
"data/world.json"
"data/font.png"
"data/%s.glb"
"data/Monster.bcf"
"data/test1.bcf"
"data/player.bmf"
"data/world.bwf"
"data/world.bmf"

**Comment by moefh** [comment]
Hello!

I've added some test data files (models, images and shaders) that are needed to run the game engine and the editor in their current state.

Please let me know if there's any problem using them.
